# These are options for including a sponsor button in this repository, see
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
custom: ["https://web-production-589d3f.up.railway.app"]
